printWidth: 100
bracketSameLine: true
bracketSpacing: true
useTabs: false
tabWidth: 2
singleQuote: false

plugins:
  - "prettier-plugin-svelte"

overrides:
  - files: "*.svelte"
    options:
      parser: "svelte"
